const productData = [
  {
    sku: "jvc200123",
    type: "card",
    name: "Acme Disc",
    price: "1.00 $",
    size: "700 MB",
  },
  {
    sku: "jvc200123",
    type: "card",
    name: "Acme Disc",
    price: "1.00 $",
    size: "700 MB",
  },
  {
    sku: "jvc200123",
    type: "card",
    name: "Acme Disc",
    price: "1.00 $",
    size: "700 MB",
  },
  {
    sku: "jvc200123",
    type: "card",
    name: "Acme Disc",
    price: "1.00 $",
    size: "700 MB",
  },
  {
    sku: "ggwp0007",
    type: "book",
    name: "War and Peace",
    price: "20.00 $",
    size: "Weight: 2 KG",
  },
  {
    sku: "ggwp0007",
    type: "book",
    name: "War and Peace",
    price: "20.00 $",
    size: "Weight: 2 KG",
  },
  {
    sku: "ggwp0007",
    type: "book",
    name: "War and Peace",
    price: "20.00 $",
    size: "Weight: 2 KG",
  },
  {
    sku: "ggwp0007",
    type: "book",
    name: "War and Peace",
    price: "20.00 $",
    size: "Weight: 2 KG",
  },
  {
    sku: "tr120555",
    type: "furniture",
    name: "Chair",
    price: "40.00 $",
    size: "Dimension: 24x45x15",
  },
  {
    sku: "tr120555",
    type: "furniture",
    name: "Chair",
    price: "40.00 $",
    size: "Dimension: 24x45x15",
  },
  {
    sku: "tr120555",
    type: "furniture",
    name: "Chair",
    price: "40.00 $",
    size: "Dimension: 24x45x15",
  },
  {
    sku: "tr120555",
    type: "furniture",
    name: "Chair",
    price: "40.00 $",
    size: "Dimension: 24x45x15",
  },
];

export default productData